
name: Deploy to VPS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Tarik Kode dan Jalankan Aplikasi
      run: |
        cd ~/my-cloud-app
        git pull origin main
        npm install --production
        pm2 reload my-cloud-app --update-env
        echo "Deployment completed at $(date)"
